version: '2'
services:
  consul-s1:
    image: consul:1.10
    container_name: consul-s1
    command: ["agent"]
    volumes:
      - /Users/martial/consul-work/data/consul-s1-data:/consul/data
      - /Users/martial/consul-work/configs/consul-s1:/consul/config
    networks:
      consul-net:
        ipv4_address: 172.18.0.10
  consul-s2:
    image: consul:1.10
    container_name: consul-s2
    command: ["agent"]
    volumes:
      - /Users/martial/consul-work/data/consul-s2-data:/consul/data
      - /Users/martial/consul-work/configs/consul-s2:/consul/config
    networks:
      consul-net:
        ipv4_address: 172.18.0.11
  consul-s3:
    image: consul:1.12.2
    container_name: consul-s3
    command: ["agent"]
    volumes:
      - /Users/martial/consul-work/data/consul-s3-data:/consul/data
      - /Users/martial/consul-work/configs/consul-s3:/consul/config
    networks:
      consul-net:
        ipv4_address: 172.18.0.12
  consul-c:
    image: consul:1.10
    container_name: consul-c
    command: ["agent"]
    volumes:
      - /Users/martial/consul-work/data/consul-c-data:/consul/data
      - /Users/martial/consul-work/configs/consul-c:/consul/config
    ports:
      - "8500:8500"
    networks:
      consul-net:
        ipv4_address: 172.18.0.13
  vault-server:
    image: vault:1.4.0
    container_name: vault-server
    volumes:
      - /Users/martial/consul-work/data/vault-server-logs:/vault/logs
      - /Users/martial/consul-work/configs/vault-server:/vault/config
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    entrypoint: vault server -config /vault/config
    networks:
      consul-net:
        ipv4_address: 172.18.0.14

networks:
  # consul-net:
  #   driver: bridge
  #   name: consul-net
  #   ipam:
  #     config:
  #       - subnet: 172.18.0.0/24
  #         gateway: 172.18.0.1
  consul-net:
    name: consul-net
    external: true
